### ISSUE TITLE
Making sure you're aware of GPack

### ISSUE THREAD

**Issue by RollingStar** [LedZeppelin68/i-merger#1]
Without knowing anything about your project, I want to be sure you know about GPack. https://github.com/RollingStar/GPack-Unofficial

**Comment by LedZeppelin68** [comment]
Hello, I think, I remember this tool, but since i started "Walrus CD/DVD Merger" about 5 years ago i want to continue development of my own and finish it :)

**Comment by RollingStar** [comment]
No worries; good luck!
